import { useState, useEffect, useRef } from 'react'

// ── Helpers ───────────────────────────────────────────────────────────────────

function fmt(type) {
  return (type || '').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
}

function formatTs(iso) {
  if (!iso) return ''
  return new Date(iso).toLocaleString(undefined, {
    month: 'short', day: 'numeric', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

// ── Verdict logic ─────────────────────────────────────────────────────────────

function deriveVerdict(out) {
  const outcome = out?.playerOutcomes?.yourCompany?.outcome
  const hasBetter = Boolean(out?.betterAlternative?.move)

  if (outcome === 'loses' || outcome === 'loses_significantly') {
    return { verdict: 'REVISE STRATEGY', color: '#dc2626', bg: '#450a0a', border: '#7f1d1d', dot: 'bg-red-500', tag: 'red' }
  }
  if (outcome === 'wins' || outcome === 'gains') {
    if (hasBetter) {
      return { verdict: 'PROCEED WITH CAUTION', color: '#d97706', bg: '#1c1400', border: '#78350f', dot: 'bg-amber-400', tag: 'amber' }
    }
    return { verdict: 'PROCEED', color: '#16a34a', bg: '#052e16', border: '#14532d', dot: 'bg-emerald-500', tag: 'green' }
  }
  // neutral outcome: revise if there's a clear alternative, otherwise caution
  if (hasBetter) {
    return { verdict: 'REVISE STRATEGY', color: '#dc2626', bg: '#450a0a', border: '#7f1d1d', dot: 'bg-red-500', tag: 'red' }
  }
  return { verdict: 'PROCEED WITH CAUTION', color: '#d97706', bg: '#1c1400', border: '#78350f', dot: 'bg-amber-400', tag: 'amber' }
}

// ── Evidence badge ────────────────────────────────────────────────────────────

const EVIDENCE_STYLES = {
  'Known Fact':          { bg: '#0c2340', text: '#7dd3fc', border: '#1e4976' },
  'User Input':          { bg: '#1a0a2e', text: '#c4b5fd', border: '#3b1f6e' },
  'Assumption':          { bg: '#1c1400', text: '#fbbf24', border: '#78350f' },
  'Model Inference':     { bg: '#111827', text: '#9ca3af', border: '#374151' },
  'Derived Calculation': { bg: '#0a1f1a', text: '#6ee7b7', border: '#134e3a' },
}

function EvidenceBadge({ tag }) {
  if (!tag) return null
  const s = EVIDENCE_STYLES[tag] ?? EVIDENCE_STYLES['Model Inference']
  return (
    <span
      className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-semibold leading-none whitespace-nowrap"
      style={{ background: s.bg, color: s.text, border: `1px solid ${s.border}` }}
    >
      {tag}
    </span>
  )
}

function EvidenceLegend() {
  return (
    <div className="rounded-xl p-4" style={{ background: '#0d1117', border: '1px solid #1f2937' }}>
      <p className="text-xs font-bold uppercase tracking-widest mb-3" style={{ color: '#4a7fa5' }}>Evidence Legend</p>
      <div className="flex flex-wrap gap-3">
        {Object.entries(EVIDENCE_STYLES).map(([label, s]) => (
          <div key={label} className="flex items-center gap-2">
            <span
              className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-semibold leading-none"
              style={{ background: s.bg, color: s.text, border: `1px solid ${s.border}` }}
            >
              {label}
            </span>
            <span className="text-xs text-gray-500">{EVIDENCE_LEGEND_DESC[label]}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

const EVIDENCE_LEGEND_DESC = {
  'Known Fact':          'externally observed or source-backed',
  'User Input':          'directly provided by you',
  'Assumption':          'planning assumption, not guaranteed',
  'Model Inference':     'generated by the simulation',
  'Derived Calculation': 'computed from input values',
}

// ── Primitive UI ──────────────────────────────────────────────────────────────

function SectionLabel({ children }) {
  return (
    <p className="text-xs font-bold uppercase tracking-widest mb-3" style={{ color: '#4a7fa5' }}>
      {children}
    </p>
  )
}

function Divider() {
  return <div className="border-t" style={{ borderColor: '#1f2937' }} />
}

function TimingBadge({ timing }) {
  const map = {
    immediate:       { label: 'Immediate',      cls: 'bg-red-900/60 text-red-300 border-red-800' },
    within_30_days:  { label: '< 30 days',      cls: 'bg-amber-900/60 text-amber-300 border-amber-800' },
    within_quarter:  { label: 'This quarter',   cls: 'bg-blue-900/60 text-blue-300 border-blue-800' },
    wait_and_see:    { label: 'Wait & see',     cls: 'bg-gray-800 text-gray-400 border-gray-700' },
  }
  const { label, cls } = map[timing] ?? { label: timing ?? '—', cls: 'bg-gray-800 text-gray-400 border-gray-700' }
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium border ${cls}`}>
      {label}
    </span>
  )
}

function ThreatBadge({ cap, agg }) {
  if (cap >= 70 && agg >= 70) return <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold border bg-red-900/60 text-red-300 border-red-800">HIGH</span>
  if (cap >= 40 && agg >= 45) return <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold border bg-amber-900/60 text-amber-300 border-amber-800">MEDIUM</span>
  return <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold border bg-gray-800 text-gray-400 border-gray-700">LOW</span>
}

function OutcomePill({ outcome }) {
  const map = {
    wins:               'bg-emerald-900/60 text-emerald-300 border-emerald-800',
    gains:              'bg-emerald-900/60 text-emerald-300 border-emerald-800',
    breaks_even:        'bg-blue-900/60 text-blue-300 border-blue-800',
    holds:              'bg-blue-900/60 text-blue-300 border-blue-800',
    loses:              'bg-red-900/60 text-red-300 border-red-800',
    loses_significantly:'bg-red-900/60 text-red-300 border-red-800',
  }
  const cls = map[outcome] ?? 'bg-gray-800 text-gray-400 border-gray-700'
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded border text-xs font-semibold ${cls}`}>
      {fmt(outcome)}
    </span>
  )
}

// ── Section 0: Decision Brief ─────────────────────────────────────────────────

function ConfidenceBadge({ level }) {
  const map = {
    High:   'bg-emerald-900/60 text-emerald-300 border-emerald-800',
    Medium: 'bg-amber-900/60 text-amber-300 border-amber-800',
    Low:    'bg-red-900/60 text-red-300 border-red-800',
  }
  const cls = map[level] ?? 'bg-gray-800 text-gray-400 border-gray-700'
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded border text-xs font-bold tracking-wide ${cls}`}>
      {level ?? '—'}
    </span>
  )
}

function DecisionBriefCard({ brief, ec }) {
  if (!brief) return null
  const { recommendedDecision, confidenceLevel, confidenceRationale, primaryReason, biggestWatchout, decisionGate, executiveSummary } = brief
  const ecb = ec?.decisionBrief ?? {}

  return (
    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1e3a5f', borderTopWidth: '2px', borderTopColor: '#3b82f6' }}>
      {/* Header */}
      <div className="px-5 py-3 flex items-center justify-between" style={{ background: '#060e1a', borderBottom: '1px solid #1e3a5f' }}>
        <p className="text-xs font-bold uppercase tracking-widest" style={{ color: '#4a7fa5' }}>Decision Brief</p>
        <ConfidenceBadge level={confidenceLevel} />
      </div>

      {/* Body: two-column on md+ */}
      <div className="grid grid-cols-1 md:grid-cols-5" style={{ background: '#0a1628' }}>

        {/* Left — recommendation + summary */}
        <div className="md:col-span-3 px-5 py-5 space-y-3" style={{ borderRight: '1px solid #1e3a5f' }}>
          <div className="flex items-start gap-2 flex-wrap">
            <p className="text-base font-bold text-white leading-snug flex-1">{recommendedDecision}</p>
            <EvidenceBadge tag={ecb.recommendedDecision} />
          </div>

          {confidenceRationale && (
            <p className="text-xs leading-relaxed" style={{ color: '#94a3b8' }}>
              <span className="font-semibold" style={{ color: '#7dd3fc' }}>Confidence: </span>
              {confidenceRationale}
            </p>
          )}

          {executiveSummary && (
            <p className="text-xs text-gray-400 leading-relaxed pt-1" style={{ borderTop: '1px solid #1e3a5f' }}>
              {executiveSummary}
            </p>
          )}
        </div>

        {/* Right — three signal rows */}
        <div className="md:col-span-2">
          {[
            { icon: '→', label: 'Primary Reason',   text: primaryReason,   color: '#34d399', ecKey: 'primaryReason' },
            { icon: '▲', label: 'Biggest Watchout',  text: biggestWatchout, color: '#f59e0b', ecKey: 'biggestWatchout' },
            { icon: '◎', label: 'Decision Gate',     text: decisionGate,    color: '#818cf8', ecKey: 'decisionGate' },
          ].map(({ icon, label, text, color, ecKey }, i) => (
            <div key={label} className="px-5 py-3.5 flex items-start gap-3" style={{ borderTop: i > 0 ? '1px solid #1e3a5f' : undefined }}>
              <span className="text-sm shrink-0 mt-0.5" style={{ color }}>{icon}</span>
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <p className="text-xs font-bold uppercase tracking-wider" style={{ color: '#4a7fa5' }}>{label}</p>
                  <EvidenceBadge tag={ecb[ecKey]} />
                </div>
                <p className="text-xs text-gray-300 leading-relaxed">{text ?? '—'}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// ── Assumptions Used table ────────────────────────────────────────────────────

const SOURCE_STYLES = {
  'User Input':      { bg: '#1a0a2e', text: '#c4b5fd', border: '#3b1f6e' },
  'Model Inference': { bg: '#111827', text: '#9ca3af', border: '#374151' },
  'Default':         { bg: '#0d1117', text: '#6b7280', border: '#1f2937' },
}

const CONFIDENCE_STYLES = {
  High:   { bg: '#052e16', text: '#86efac', border: '#14532d' },
  Medium: { bg: '#1c1400', text: '#fbbf24', border: '#78350f' },
  Low:    { bg: '#450a0a', text: '#fca5a5', border: '#7f1d1d' },
}

function SourceBadge({ type }) {
  const s = SOURCE_STYLES[type] ?? SOURCE_STYLES['Default']
  return (
    <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-semibold leading-none whitespace-nowrap"
      style={{ background: s.bg, color: s.text, border: `1px solid ${s.border}` }}>
      {type ?? '—'}
    </span>
  )
}

function ConfidencePill({ level }) {
  const s = CONFIDENCE_STYLES[level] ?? CONFIDENCE_STYLES['Medium']
  return (
    <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold leading-none whitespace-nowrap"
      style={{ background: s.bg, color: s.text, border: `1px solid ${s.border}` }}>
      {level ?? '—'}
    </span>
  )
}

function AssumptionsUsedTable({ assumptions }) {
  if (!assumptions?.length) return null
  const [expanded, setExpanded] = useState(null)

  return (
    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1f2937' }}>
      {/* Header */}
      <div className="px-5 py-3 flex items-center justify-between" style={{ background: '#0d1117', borderBottom: '1px solid #1f2937' }}>
        <p className="text-xs font-bold uppercase tracking-widest" style={{ color: '#4a7fa5' }}>Assumptions Used</p>
        <span className="text-xs text-gray-600">{assumptions.length} assumption{assumptions.length !== 1 ? 's' : ''}</span>
      </div>

      {/* Column headers */}
      <div className="hidden md:grid px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-gray-600"
        style={{ gridTemplateColumns: '2fr 1.6fr 1.1fr 0.7fr 2.4fr', background: '#0a0f1a', borderBottom: '1px solid #1f2937' }}>
        <div>Assumption</div>
        <div>Value</div>
        <div>Source</div>
        <div>Confidence</div>
        <div>Impact if Wrong</div>
      </div>

      {/* Rows */}
      {assumptions.map((row, i) => {
        const isOpen = expanded === i
        return (
          <div
            key={i}
            className="px-4 py-3"
            style={{ borderTop: i > 0 ? '1px solid #1f2937' : undefined, background: i % 2 === 0 ? '#111827' : '#0f172a' }}
          >
            {/* Desktop grid */}
            <div className="hidden md:grid items-start gap-x-4"
              style={{ gridTemplateColumns: '2fr 1.6fr 1.1fr 0.7fr 2.4fr' }}>
              <p className="text-xs font-semibold text-gray-200 leading-relaxed">{row.assumption}</p>
              <p className="text-xs text-gray-300 leading-relaxed">{row.value ?? '—'}</p>
              <div><SourceBadge type={row.sourceType} /></div>
              <div><ConfidencePill level={row.confidence} /></div>
              <p className="text-xs text-gray-400 leading-relaxed">{row.impactIfWrong ?? '—'}</p>
            </div>

            {/* Mobile stacked */}
            <div className="md:hidden">
              <button
                className="w-full flex items-center justify-between gap-2 text-left"
                onClick={() => setExpanded(isOpen ? null : i)}
              >
                <p className="text-xs font-semibold text-gray-200">{row.assumption}</p>
                <div className="flex items-center gap-1.5 shrink-0">
                  <ConfidencePill level={row.confidence} />
                  <span className="text-gray-600 text-xs">{isOpen ? '▲' : '▼'}</span>
                </div>
              </button>
              {isOpen && (
                <div className="mt-2 space-y-1.5 pl-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] text-gray-600 uppercase tracking-wider w-14">Value</span>
                    <p className="text-xs text-gray-300">{row.value ?? '—'}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] text-gray-600 uppercase tracking-wider w-14">Source</span>
                    <SourceBadge type={row.sourceType} />
                  </div>
                  <div className="flex items-start gap-2 mt-1">
                    <span className="text-[10px] text-gray-600 uppercase tracking-wider w-14 pt-0.5">Impact</span>
                    <p className="text-xs text-gray-400 leading-relaxed">{row.impactIfWrong ?? '—'}</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        )
      })}
    </div>
  )
}

// ── Strategic Options Comparison ──────────────────────────────────────────────

const ASSESSMENT_STYLES = {
  'Preferred':        { bg: '#052e16', text: '#86efac', border: '#14532d', dot: '#22c55e' },
  'Viable':           { bg: '#0c2340', text: '#7dd3fc', border: '#1e4976', dot: '#38bdf8' },
  'Risky':            { bg: '#1c1400', text: '#fbbf24', border: '#78350f', dot: '#f59e0b' },
  'Not Recommended':  { bg: '#450a0a', text: '#fca5a5', border: '#7f1d1d', dot: '#ef4444' },
}

const RISK_STYLES = {
  High:   { text: '#fca5a5' },
  Medium: { text: '#fbbf24' },
  Low:    { text: '#86efac' },
}

function RiskCell({ level }) {
  const s = RISK_STYLES[level] ?? RISK_STYLES['Medium']
  return <span className="text-xs font-semibold" style={{ color: s.text }}>{level ?? '—'}</span>
}

function AssessmentBadge({ assessment }) {
  const s = ASSESSMENT_STYLES[assessment] ?? ASSESSMENT_STYLES['Viable']
  return (
    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-bold leading-none whitespace-nowrap"
      style={{ background: s.bg, color: s.text, border: `1px solid ${s.border}` }}>
      <span className="w-1.5 h-1.5 rounded-full shrink-0" style={{ background: s.dot }} />
      {assessment}
    </span>
  )
}

const FINANCIAL_COLS = [
  { key: 'revenueUpside', label: 'Revenue Upside', hint: '↑ higher is better' },
  { key: 'volumeRisk',    label: 'Volume Risk',    hint: '↓ downside if wrong' },
]

const QUALITATIVE_COLS = [
  { key: 'competitorRisk',           label: 'Competitor Risk', hint: '↓ lower is better' },
  { key: 'retailerOrCustomerRisk',   label: 'Cust. Risk',      hint: '↓ lower is better' },
  { key: 'implementationComplexity', label: 'Complexity',      hint: '↓ lower is better' },
]

function StrategicOptionsTable({ options }) {
  if (!options?.length) return null

  return (
    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1f2937' }}>
      <div className="px-5 py-3" style={{ background: '#0d1117', borderBottom: '1px solid #1f2937' }}>
        <p className="text-xs font-bold uppercase tracking-widest" style={{ color: '#4a7fa5' }}>Strategic Options Comparison</p>
        <p className="text-xs text-gray-600 mt-0.5">Why this recommendation over the alternatives</p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-xs" style={{ borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: '#0a0f1a', borderBottom: '1px solid #1f2937' }}>
              <th className="text-left px-4 py-2.5 align-top" style={{ minWidth: 160 }}>
                <span className="font-bold uppercase tracking-wider text-gray-600">Option</span>
              </th>
              {FINANCIAL_COLS.map(c => (
                <th key={c.key} className="text-left px-3 py-2.5 align-top whitespace-nowrap" style={{ minWidth: 140 }}>
                  <span className="font-bold uppercase tracking-wider text-gray-600 block">{c.label}</span>
                  <span className="text-gray-700 font-normal normal-case tracking-normal" style={{ fontSize: 10 }}>{c.hint}</span>
                </th>
              ))}
              {QUALITATIVE_COLS.map(c => (
                <th key={c.key} className="text-center px-3 py-2.5 align-top whitespace-nowrap">
                  <span className="font-bold uppercase tracking-wider text-gray-600 block">{c.label}</span>
                  <span className="text-gray-700 font-normal normal-case tracking-normal" style={{ fontSize: 10 }}>{c.hint}</span>
                </th>
              ))}
              <th className="text-left px-4 py-2.5 align-top whitespace-nowrap">
                <span className="font-bold uppercase tracking-wider text-gray-600">Assessment</span>
              </th>
              <th className="text-left px-4 py-2.5 align-top" style={{ minWidth: 220 }}>
                <span className="font-bold uppercase tracking-wider text-gray-600">Rationale</span>
              </th>
            </tr>
          </thead>
          <tbody>
            {options.map((opt, i) => {
              const isPreferred = opt.overallAssessment === 'Preferred'
              const rowBg = isPreferred ? '#061a10' : i % 2 === 0 ? '#111827' : '#0f172a'
              return (
                <tr key={i} style={{ background: rowBg, borderTop: '1px solid #1f2937' }}>
                  {/* Option name + description */}
                  <td className="px-4 py-3 align-top" style={{ borderLeft: isPreferred ? '2px solid #22c55e' : '2px solid transparent' }}>
                    <p className="font-semibold text-gray-100 mb-0.5">{opt.optionName}</p>
                    <p className="text-gray-500 leading-relaxed" style={{ maxWidth: 200 }}>{opt.description}</p>
                  </td>

                  {/* Financial cells — plain text, anchored ranges */}
                  {FINANCIAL_COLS.map(c => (
                    <td key={c.key} className="px-3 py-3 align-top">
                      <p className="text-gray-300 leading-relaxed">{opt[c.key] ?? '—'}</p>
                    </td>
                  ))}

                  {/* Qualitative cells — color-coded High/Medium/Low */}
                  {QUALITATIVE_COLS.map(c => (
                    <td key={c.key} className="px-3 py-3 text-center align-top">
                      <RiskCell level={opt[c.key]} />
                    </td>
                  ))}

                  {/* Assessment badge */}
                  <td className="px-4 py-3 align-top whitespace-nowrap">
                    <AssessmentBadge assessment={opt.overallAssessment} />
                  </td>

                  {/* Rationale */}
                  <td className="px-4 py-3 align-top">
                    <p className="text-gray-400 leading-relaxed">{opt.rationale}</p>
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// ── Section 1: Verdict banner ─────────────────────────────────────────────────

function VerdictBanner({ out, result }) {
  const v = deriveVerdict(out)
  const { equilibriumReached, totalRounds } = result
  const yourOutcome = out?.playerOutcomes?.yourCompany

  return (
    <div className="rounded-xl p-5" style={{ background: v.bg, border: `1px solid ${v.border}` }}>
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className={`w-3 h-3 rounded-full shrink-0 ${v.dot}`} />
          <div>
            <p className="text-xs font-bold uppercase tracking-widest mb-0.5" style={{ color: v.color, opacity: 0.7 }}>AI Recommendation</p>
            <p className="text-2xl font-bold" style={{ color: v.color }}>{v.verdict}</p>
          </div>
        </div>
        <div className="flex flex-wrap gap-3 text-xs">
          {yourOutcome && (
            <div className="text-right">
              <p className="text-gray-500 mb-1">Your outcome</p>
              <OutcomePill outcome={yourOutcome.outcome} />
            </div>
          )}
          <div className="text-right">
            <p className="text-gray-500 mb-1">Simulation</p>
            <span className="inline-flex items-center px-2 py-0.5 rounded border border-gray-700 bg-gray-800 text-gray-300 text-xs font-medium">
              {totalRounds} round{totalRounds !== 1 ? 's' : ''} · {equilibriumReached ? 'Equilibrium reached' : 'Equilibrium pending'}
            </span>
          </div>
        </div>
      </div>
      {yourOutcome?.reasoning && (
        <p className="text-sm mt-4 leading-relaxed" style={{ color: v.color, opacity: 0.75 }}>
          {yourOutcome.reasoning}
        </p>
      )}
    </div>
  )
}

// ── Section 1b: Priority actions ─────────────────────────────────────────────

function PriorityActionsPanel({ actions, ec }) {
  if (!actions?.length) return null
  return (
    <div
      className="rounded-xl p-5"
      style={{ background: '#0a1628', border: '1px solid #1e3a5f', borderTopWidth: '2px', borderTopColor: '#0ea5e9' }}
    >
      <SectionLabel>What to Do Now</SectionLabel>
      <div className="space-y-3">
        {actions.map((action, i) => {
          const text = action.replace(/^\d+\.\s*/, '')
          return (
            <div key={i} className="flex items-start gap-3">
              <span
                className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold shrink-0 mt-0.5"
                style={{ background: '#0ea5e9', color: '#0f172a' }}
              >
                {i + 1}
              </span>
              <div className="flex-1">
                <p className="text-sm text-gray-100 leading-relaxed">{text}</p>
                {ec?.priorityActions?.[i] && (
                  <div className="mt-1.5"><EvidenceBadge tag={ec.priorityActions[i]} /></div>
                )}
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ── Section 2: Recommendation + Market snapshot ───────────────────────────────

function RecommendationPanel({ out, ec }) {
  const { strategicRecommendation, betterAlternative, marketEquilibrium } = out

  return (
    <div>
      {/* ── Strategic Recommendation — hidden, restore by uncommenting ──────────
      <div className="rounded-xl p-5 mb-4" style={{ background: '#0f172a', border: '1px solid #1e3a5f' }}>
        <SectionLabel>Strategic Recommendation</SectionLabel>
        <p className="text-sm text-gray-200 leading-relaxed">{strategicRecommendation}</p>

        {betterAlternative && (
          <div className="mt-4 p-4 rounded-lg" style={{ background: '#0b1426', border: '1px solid #1e3a5f' }}>
            <p className="text-xs font-bold uppercase tracking-wider mb-2" style={{ color: '#0ea5e9' }}>Consider instead</p>
            <p className="text-sm font-semibold text-white mb-1">{betterAlternative.move}</p>
            <p className="text-sm text-gray-400 leading-relaxed mb-3">{betterAlternative.reasoning}</p>
            <div className="pt-3" style={{ borderTop: '1px solid #1e3a5f' }}>
              <p className="text-xs text-gray-500 font-medium mb-1">Expected outcome</p>
              <p className="text-xs text-gray-300 leading-relaxed">{betterAlternative.expectedOutcome}</p>
            </div>
          </div>
        )}
      </div>
      ─────────────────────────────────────────────────────────────────────── */}

      {/* Market Equilibrium — full width */}
      <div className="rounded-xl p-5" style={{ background: '#111827', border: '1px solid #1f2937' }}>
        <SectionLabel>Market Equilibrium</SectionLabel>
        <div className="flex items-start gap-2 flex-wrap mb-4">
          <p className="text-xs text-gray-400 leading-relaxed flex-1">{marketEquilibrium}</p>
          <EvidenceBadge tag={ec?.marketEquilibrium} />
        </div>

        {out.playerOutcomes && (
          <div className="space-y-3">
            {Object.entries(out.playerOutcomes).map(([key, val]) => (
              <div
                key={key}
                className="rounded-lg px-3 py-2.5 space-y-1.5"
                style={{ background: '#0d1117', border: '1px solid #1f2937' }}
              >
                {/* Name + outcome pill + evidence badge */}
                <div className="flex items-center justify-between gap-2 flex-wrap">
                  <span className="text-xs font-semibold text-gray-200 truncate">
                    {key === 'yourCompany' ? (out._yourCompanyName ?? 'You') : key}
                  </span>
                  <div className="flex items-center gap-1.5">
                    <EvidenceBadge tag={ec?.playerOutcomes?.[key]} />
                    <OutcomePill outcome={val.outcome} />
                  </div>
                </div>
                {val.reasoning && (
                  <p className="text-xs text-gray-400 leading-relaxed">{val.reasoning}</p>
                )}
                {val.financialEstimate && (
                  <p className="text-xs leading-relaxed" style={{ color: '#f59e0b' }}>
                    {val.financialEstimate}
                  </p>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Legend */}
        <div className="mt-3 pt-3 space-y-1.5" style={{ borderTop: '1px solid #1f2937' }}>
          <p className="text-xs font-bold uppercase tracking-widest mb-2" style={{ color: '#4a7fa5' }}>Legend</p>
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full shrink-0" style={{ background: '#34d399' }} />
            <p className="text-xs text-gray-500"><span className="text-gray-400 font-medium">Wins</span> — gains or protects share / margin vs. pre-move baseline</p>
          </div>
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full shrink-0" style={{ background: '#60a5fa' }} />
            <p className="text-xs text-gray-500"><span className="text-gray-400 font-medium">Neutral</span> — no material change to competitive position</p>
          </div>
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full shrink-0" style={{ background: '#f87171' }} />
            <p className="text-xs text-gray-500"><span className="text-gray-400 font-medium">Loses</span> — gives up market share, margin, or revenue</p>
          </div>
        </div>
      </div>
    </div>
  )
}

// ── Section 3: Competitive response matrix ────────────────────────────────────

function competitorFinalData(r1entry, r2entry) {
  const r2 = r2entry?.response
  const r1resp = r1entry?.response
  const final = r2?.primaryResponse ?? r1resp?.primaryResponse
  const watch = r2?.watchSignal ?? r1resp?.watchSignal
  const cap = r1entry.profile?.financialCapacityScore ?? 0
  const agg = r1entry.profile?.aggressionIndex ?? 0
  const typeChanged = r2 && r1resp?.primaryResponse?.type !== r2?.primaryResponse?.type

  const isMagnitudeIntensity = ['bundle_add', 'marketing_surge', 'niche_pivot', 'alliance', 'no_response'].includes(final?.type)
  const magnitude = final?.magnitude > 0
    ? (isMagnitudeIntensity ? `${final.magnitude}/10 intensity` : `${final.magnitude}%`)
    : null

  return { final, watch, cap, agg, typeChanged, magnitude, rationale: final?.rationale }
}

function ImplicationCell({ text }) {
  const [expanded, setExpanded] = useState(false)
  if (!text || text === '—') return <p className="text-xs text-gray-600">—</p>
  return (
    <div>
      <p className={`text-xs text-gray-400 leading-relaxed ${expanded ? '' : 'line-clamp-3'}`}>
        {text}
      </p>
      <button
        onClick={() => setExpanded(e => !e)}
        className="mt-1.5 text-xs font-medium text-sky-500 hover:text-sky-400 transition-colors"
      >
        {expanded ? 'See less ↑' : 'See more ↓'}
      </button>
    </div>
  )
}

function CompetitiveResponseMatrix({ result }) {
  const { rounds } = result
  const r1 = rounds?.round1 ?? []
  const r2 = rounds?.round2 ?? []

  if (r1.length === 0) return null

  return (
    <div>
      <SectionLabel>Competitive Response Matrix</SectionLabel>
      <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1f2937' }}>
        {/* Table header */}
        <div className="grid text-xs font-bold uppercase tracking-wider text-gray-500 px-4 py-3"
          style={{ gridTemplateColumns: '1.2fr 1.8fr 1fr 0.7fr 2fr', background: '#0d1117', borderBottom: '1px solid #1f2937' }}>
          <div>Competitor</div>
          <div>Expected Response</div>
          <div>Timing</div>
          <div>Threat</div>
          <div>Implication for You</div>
        </div>

        {r1.map((entry, i) => {
          const { final, watch, cap, agg, typeChanged, magnitude } = competitorFinalData(entry, r2[i])
          const implication = watch ?? final?.rationale ?? '—'

          return (
            <div
              key={entry.competitorName}
              className="grid items-start px-4 py-4 text-sm gap-x-4"
              style={{
                gridTemplateColumns: '1.2fr 1.8fr 1fr 0.7fr 2fr',
                borderTop: i > 0 ? '1px solid #1f2937' : undefined,
                background: i % 2 === 0 ? '#111827' : '#0f172a',
              }}
            >
              {/* Competitor */}
              <div>
                <p className="font-semibold text-white text-sm">{entry.competitorName}</p>
                {typeChanged && (
                  <span className="text-xs text-indigo-400 mt-0.5">↻ Adjusted</span>
                )}
              </div>

              {/* Response */}
              <div>
                <p className="font-medium text-gray-200">{fmt(final?.type)}</p>
                {magnitude && <p className="text-xs text-gray-500 mt-0.5">{magnitude}</p>}
              </div>

              {/* Timing */}
              <div>
                <TimingBadge timing={final?.timing} />
              </div>

              {/* Threat */}
              <div>
                <ThreatBadge cap={cap} agg={agg} />
              </div>

              {/* Implication */}
              <div>
                <ImplicationCell text={implication} />
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ── Section 4: Scenario outcomes ──────────────────────────────────────────────

function ScenarioOutcomes({ bands, ec }) {
  if (!bands) return null
  const cols = [
    { key: 'bestCase',   label: 'Best Case',   border: '#14532d', bg: '#052e16', labelColor: '#86efac' },
    { key: 'likelyCase', label: 'Base Case',   border: '#1e3a5f', bg: '#0f172a', labelColor: '#93c5fd' },
    { key: 'worstCase',  label: 'Worst Case',  border: '#7f1d1d', bg: '#450a0a', labelColor: '#fca5a5' },
  ]

  return (
    <div>
      <SectionLabel>Scenario Range</SectionLabel>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {cols.map(({ key, label, border, bg, labelColor }) => {
          const band = bands[key]
          if (!band) return null
          return (
            <div key={key} className="rounded-xl p-4" style={{ background: bg, border: `1px solid ${border}` }}>
              <div className="flex items-center justify-between mb-3">
                <p className="text-xs font-bold uppercase tracking-wider" style={{ color: labelColor }}>{label}</p>
                <EvidenceBadge tag={ec?.confidenceBands?.[key]} />
              </div>
              <p className="text-sm text-gray-200 leading-relaxed mb-3">{band.description}</p>
              <div className="pt-3" style={{ borderTop: `1px solid ${border}` }}>
                <p className="text-xs text-gray-500 font-medium mb-1">Conditions</p>
                <p className="text-xs text-gray-400 leading-relaxed">{band.conditions}</p>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ── Recommendation Change Triggers ───────────────────────────────────────────

const URGENCY_STYLES = {
  High:   { bg: '#450a0a', text: '#fca5a5', border: '#7f1d1d' },
  Medium: { bg: '#1c1400', text: '#fbbf24', border: '#78350f' },
  Low:    { bg: '#0c2340', text: '#7dd3fc', border: '#1e4976' },
}

function UrgencyBadge({ urgency }) {
  const s = URGENCY_STYLES[urgency] ?? URGENCY_STYLES['Medium']
  return (
    <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold leading-none whitespace-nowrap"
      style={{ background: s.bg, color: s.text, border: `1px solid ${s.border}` }}>
      {urgency}
    </span>
  )
}

function RecommendationChangeTriggers({ triggers }) {
  if (!triggers?.length) return null
  return (
    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1f2937' }}>
      <div className="px-5 py-3" style={{ background: '#0d1117', borderBottom: '1px solid #1f2937' }}>
        <p className="text-xs font-bold uppercase tracking-widest" style={{ color: '#4a7fa5' }}>What Would Change Our Recommendation?</p>
        <p className="text-xs text-gray-600 mt-0.5">Monitor these signals after the decision is made</p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-xs" style={{ borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: '#0a0f1a', borderBottom: '1px solid #1f2937' }}>
              {[
                { label: 'Trigger',             hint: null,                   w: 180 },
                { label: 'Metric to Monitor',   hint: null,                   w: 160 },
                { label: 'Threshold',           hint: 'quantitative where possible', w: 140 },
                { label: 'Time Window',         hint: null,                   w: 110 },
                { label: 'Recommendation Impact', hint: 'what changes if triggered', w: 220 },
                { label: 'Urgency',             hint: null,                   w: 80  },
              ].map(({ label, hint, w }) => (
                <th key={label} className="text-left px-4 py-2.5 align-top" style={{ minWidth: w }}>
                  <span className="font-bold uppercase tracking-wider text-gray-600 block">{label}</span>
                  {hint && <span className="text-gray-700 font-normal normal-case tracking-normal" style={{ fontSize: 10 }}>{hint}</span>}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {triggers.map((t, i) => {
              const isHigh = t.urgency === 'High'
              return (
                <tr key={i} style={{
                  borderTop: '1px solid #1f2937',
                  background: isHigh ? '#180808' : i % 2 === 0 ? '#111827' : '#0f172a',
                }}>
                  <td className="px-4 py-3 align-top" style={{ borderLeft: isHigh ? '2px solid #ef4444' : '2px solid transparent' }}>
                    <p className="font-semibold text-gray-100 leading-relaxed">{t.trigger}</p>
                  </td>
                  <td className="px-4 py-3 align-top">
                    <p className="text-gray-400 leading-relaxed">{t.metricToMonitor ?? '—'}</p>
                  </td>
                  <td className="px-4 py-3 align-top">
                    <p className="text-gray-200 font-medium leading-relaxed">{t.threshold ?? '—'}</p>
                  </td>
                  <td className="px-4 py-3 align-top whitespace-nowrap">
                    <p className="text-gray-400">{t.timeWindow ?? '—'}</p>
                  </td>
                  <td className="px-4 py-3 align-top">
                    <p className="text-gray-300 leading-relaxed">{t.recommendationImpact ?? '—'}</p>
                  </td>
                  <td className="px-4 py-3 align-top">
                    <UrgencyBadge urgency={t.urgency} />
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// ── 30/60/90-day Monitoring Plan ─────────────────────────────────────────────

const OWNER_STYLES = {
  'Strategy':                   { bg: '#0c2340', text: '#7dd3fc', border: '#1e4976' },
  'Finance':                    { bg: '#052e16', text: '#86efac', border: '#14532d' },
  'Sales':                      { bg: '#1a0a2e', text: '#c4b5fd', border: '#3b1f6e' },
  'Marketing':                  { bg: '#1c1400', text: '#fbbf24', border: '#78350f' },
  'Pricing':                    { bg: '#0a1f1a', text: '#6ee7b7', border: '#134e3a' },
  'Competitive Intelligence':   { bg: '#1a0d00', text: '#fb923c', border: '#7c2d12' },
  'Revenue Growth Management':  { bg: '#1a001a', text: '#e879f9', border: '#701a75' },
  'Other':                      { bg: '#111827', text: '#9ca3af', border: '#374151' },
}

function OwnerBadge({ fn }) {
  const s = OWNER_STYLES[fn] ?? OWNER_STYLES['Other']
  return (
    <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-semibold leading-none whitespace-nowrap"
      style={{ background: s.bg, color: s.text, border: `1px solid ${s.border}` }}>
      {fn ?? 'Other'}
    </span>
  )
}

function MonitoringItem({ item, accent }) {
  return (
    <div className="rounded-lg p-3 space-y-2" style={{ background: '#0d1117', border: `1px solid #1f2937`, borderLeftWidth: 2, borderLeftColor: accent }}>
      <p className="text-xs font-bold text-gray-100 leading-snug">{item.signal}</p>
      {item.whyItMatters && (
        <p className="text-xs text-gray-500 leading-relaxed">{item.whyItMatters}</p>
      )}
      <div className="flex flex-wrap gap-x-4 gap-y-1 text-[10px]">
        {item.metric && (
          <span className="text-gray-500"><span className="text-gray-400 font-semibold">Metric: </span>{item.metric}</span>
        )}
        {item.threshold && (
          <span style={{ color: accent }}><span className="font-semibold">Trigger: </span>{item.threshold}</span>
        )}
      </div>
      {item.actionIfTriggered && (
        <p className="text-[10px] text-gray-400 leading-relaxed pt-1" style={{ borderTop: '1px solid #1f2937' }}>
          <span className="font-semibold text-gray-300">If triggered: </span>{item.actionIfTriggered}
        </p>
      )}
      {item.ownerFunction && (
        <div><OwnerBadge fn={item.ownerFunction} /></div>
      )}
    </div>
  )
}

function MonitoringPlan({ plan }) {
  if (!plan) return null
  const { next30Days = [], next60Days = [], next90Days = [] } = plan
  if (!next30Days.length && !next60Days.length && !next90Days.length) return null

  const cols = [
    { key: 'next30Days', items: next30Days, label: '0–30 Days',  sublabel: 'Immediate',   accent: '#ef4444', headerBg: '#1a0505', border: '#7f1d1d' },
    { key: 'next60Days', items: next60Days, label: '30–60 Days', sublabel: 'Near-term',    accent: '#f59e0b', headerBg: '#1a1000', border: '#78350f' },
    { key: 'next90Days', items: next90Days, label: '60–90 Days', sublabel: 'Medium-term',  accent: '#38bdf8', headerBg: '#050f1a', border: '#1e3a5f' },
  ]

  return (
    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1f2937' }}>
      <div className="px-5 py-3" style={{ background: '#0d1117', borderBottom: '1px solid #1f2937' }}>
        <p className="text-xs font-bold uppercase tracking-widest" style={{ color: '#4a7fa5' }}>30 / 60 / 90-Day Monitoring Plan</p>
        <p className="text-xs text-gray-600 mt-0.5">Assign ownership and track these signals after the decision is made</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3" style={{ background: '#111827' }}>
        {cols.map(({ key, items, label, sublabel, accent, headerBg, border }, ci) => (
          <div key={key} style={{ borderLeft: ci > 0 ? '1px solid #1f2937' : undefined }}>
            {/* Column header */}
            <div className="px-4 py-2.5 flex items-center gap-2" style={{ background: headerBg, borderBottom: '1px solid #1f2937' }}>
              <span className="w-2 h-2 rounded-full shrink-0" style={{ background: accent }} />
              <div>
                <p className="text-xs font-bold" style={{ color: accent }}>{label}</p>
                <p className="text-[10px] text-gray-600">{sublabel}</p>
              </div>
              <span className="ml-auto text-[10px] text-gray-600">{items.length} signal{items.length !== 1 ? 's' : ''}</span>
            </div>

            {/* Items */}
            <div className="p-3 space-y-2">
              {items.length === 0 ? (
                <p className="text-xs text-gray-700 italic">No signals for this period.</p>
              ) : (
                items.map((item, i) => <MonitoringItem key={i} item={item} accent={accent} />)
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// ── Section 5: Watchpoints ────────────────────────────────────────────────────

function Watchpoints({ signals, risks, ec }) {
  const hasSignals = signals?.length > 0
  const hasRisks = risks?.length > 0
  if (!hasSignals && !hasRisks) return null

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      {hasSignals && (
        <div>
          <SectionLabel>Watch For These Signals</SectionLabel>
          <div className="rounded-xl overflow-hidden" style={{ background: '#111827', border: '1px solid #1f2937' }}>
            {signals.map((signal, i) => (
              <div key={i} className="flex items-start gap-3 px-4 py-3" style={{ borderTop: i > 0 ? '1px solid #1f2937' : undefined }}>
                <span className="w-5 h-5 rounded flex items-center justify-center text-xs font-bold shrink-0 mt-0.5"
                  style={{ background: '#1e3a5f', color: '#7dd3fc' }}>
                  {i + 1}
                </span>
                <div className="flex-1">
                  <p className="text-sm text-gray-300 leading-relaxed mb-1">{signal}</p>
                  <EvidenceBadge tag={ec?.watchlistSignals?.[i]} />
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {hasRisks && (
        <div>
          <SectionLabel>Key Risks</SectionLabel>
          <div className="rounded-xl overflow-hidden" style={{ background: '#111827', border: '1px solid #1f2937' }}>
            {risks.map((risk, i) => (
              <div key={i} className="flex items-start gap-3 px-4 py-3" style={{ borderTop: i > 0 ? '1px solid #1f2937' : undefined }}>
                <span className="text-amber-400 text-sm shrink-0 mt-0.5">▲</span>
                <div className="flex-1">
                  <p className="text-sm text-gray-300 leading-relaxed mb-1">{risk}</p>
                  <EvidenceBadge tag={ec?.keyRisks?.[i]} />
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// ── Section 6: Sensitivity panel ──────────────────────────────────────────────

function applyFinancialStrength(rawCompetitor, sliderVal) {
  let cashPosition, debtToEbitda
  if (sliderVal < 40) {
    cashPosition = 'weak'
    debtToEbitda = 8 - (sliderVal / 40) * 4
  } else if (sliderVal < 70) {
    cashPosition = 'moderate'
    debtToEbitda = 4 - ((sliderVal - 40) / 30) * 2
  } else {
    cashPosition = 'strong'
    debtToEbitda = 2 - ((sliderVal - 70) / 30) * 1.8
  }
  return { ...rawCompetitor, cashPosition, debtToEbitda: Math.round(debtToEbitda * 10) / 10 }
}

function extractPriceMagnitude(strategicMove) {
  const m = (strategicMove || '').match(/(\d+(\.\d+)?)\s*%/)
  return m ? parseFloat(m[1]) : 10
}

function capacityLabel(v) {
  return v < 40 ? 'Weak' : v < 70 ? 'Moderate' : 'Strong'
}

function SensitivityPanel({ baseResult, yourCompany, rawCompetitors, onResultUpdate }) {
  const firstName = rawCompetitors[0]?.name || 'Competitor A'
  const defaultCap = Math.round(baseResult.competitorProfiles?.[0]?.financialCapacityScore ?? 70)
  const defaultPrice = extractPriceMagnitude(yourCompany.strategicMove)

  const [capStrength, setCapStrength] = useState(defaultCap)
  const [priceMag, setPriceMag] = useState(defaultPrice)
  const [marketGrowth, setMarketGrowth] = useState(2)
  const [regCap, setRegCap] = useState(false)
  const [recalculating, setRecalculating] = useState(false)

  const debounceRef = useRef(null)

  useEffect(() => {
    // Only fire when the user has actually changed a value from its default.
    // Using value comparison instead of isFirstRender ref, which breaks under
    // React StrictMode (double-invoke causes the ref to flip on the discarded
    // mount, so the real mount triggers an unwanted re-run on load).
    const isDefault = capStrength === defaultCap && priceMag === defaultPrice && marketGrowth === 2 && !regCap
    if (isDefault) return
    if (debounceRef.current) clearTimeout(debounceRef.current)
    setRecalculating(true)

    debounceRef.current = setTimeout(async () => {
      try {
        const modifiedCompetitors = rawCompetitors.map((c, i) => {
          let mc = i === 0 ? applyFinancialStrength(c, capStrength) : { ...c }
          if (regCap) {
            mc = {
              ...mc,
              regulatoryConstraints: [mc.regulatoryConstraints, 'Regulatory pricing cap in effect — price changes require regulatory approval.'].filter(Boolean).join(' '),
            }
          }
          return mc
        })

        const newMove = (yourCompany.strategicMove || '').replace(/\d+(\.\d+)?\s*%/, `${priceMag}%`)
        const extraContext = marketGrowth !== 2
          ? ` Market growth rate is currently ${marketGrowth > 0 ? '+' : ''}${marketGrowth}% — ${marketGrowth > 3 ? 'a growing market reduces urgency to fight for share' : marketGrowth < 0 ? 'a shrinking market intensifies competitive pressure' : 'moderate market growth'}.`
          : ''

        const res = await fetch('http://localhost:3001/api/simulate', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            yourCompany: { ...yourCompany, strategicMove: newMove, context: (yourCompany.context || '') + extraContext },
            competitors: modifiedCompetitors,
          }),
        })
        const data = await res.json()
        if (res.ok) onResultUpdate(data)
      } catch (e) {
        console.error('[sensitivity] re-run failed:', e)
      } finally {
        setRecalculating(false)
      }
    }, 500)

    return () => clearTimeout(debounceRef.current)
  }, [capStrength, priceMag, marketGrowth, regCap])

  const sliderCls = 'w-full h-1.5 rounded-full appearance-none cursor-pointer accent-sky-500'

  return (
    <div className="relative">
      <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1f2937' }}>
        <div className="px-5 py-4" style={{ background: '#0d1117', borderBottom: '1px solid #1f2937' }}>
          <p className="text-sm font-semibold text-white">Sensitivity Analysis</p>
          <p className="text-xs text-gray-500 mt-0.5">Adjust assumptions to re-run the simulation and see how outcomes shift.</p>
        </div>

        <div className="px-5 py-5 grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-6" style={{ background: '#111827' }}>
          {/* Financial strength */}
          <div>
            <div className="flex justify-between text-xs mb-2">
              <span className="text-gray-400 font-medium">{firstName} financial strength</span>
              <span className="text-gray-200 font-semibold">{capacityLabel(capStrength)} ({capStrength})</span>
            </div>
            <input type="range" min={0} max={100} value={capStrength}
              onChange={e => setCapStrength(Number(e.target.value))} className={sliderCls} />
            <div className="flex justify-between text-xs text-gray-600 mt-1">
              <span>Weak</span><span>Moderate</span><span>Strong</span>
            </div>
          </div>

          {/* Price magnitude */}
          <div>
            <div className="flex justify-between text-xs mb-2">
              <span className="text-gray-400 font-medium">Price move magnitude</span>
              <span className="text-gray-200 font-semibold">{priceMag}%</span>
            </div>
            <input type="range" min={5} max={25} value={priceMag}
              onChange={e => setPriceMag(Number(e.target.value))} className={sliderCls} />
            <div className="flex justify-between text-xs text-gray-600 mt-1">
              <span>5%</span><span>15%</span><span>25%</span>
            </div>
          </div>

          {/* Market growth */}
          <div>
            <div className="flex justify-between text-xs mb-2">
              <span className="text-gray-400 font-medium">Market growth rate</span>
              <span className="text-gray-200 font-semibold">{marketGrowth > 0 ? '+' : ''}{marketGrowth}%</span>
            </div>
            <input type="range" min={-5} max={10} value={marketGrowth}
              onChange={e => setMarketGrowth(Number(e.target.value))} className={sliderCls} />
            <div className="flex justify-between text-xs text-gray-600 mt-1">
              <span>-5%</span><span>+2%</span><span>+10%</span>
            </div>
          </div>

          {/* Regulatory toggle */}
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-gray-400">Regulatory pricing cap</p>
              <p className="text-xs text-gray-600 mt-0.5">Limits competitor ability to respond with price cuts</p>
            </div>
            <button
              type="button"
              onClick={() => setRegCap(v => !v)}
              className={[
                'relative inline-flex h-5 w-9 shrink-0 rounded-full border-2 border-transparent transition-colors duration-200',
                regCap ? 'bg-sky-500' : 'bg-gray-700',
              ].join(' ')}
            >
              <span className={[
                'pointer-events-none inline-block h-4 w-4 rounded-full bg-white shadow transform transition-transform duration-200',
                regCap ? 'translate-x-4' : 'translate-x-0',
              ].join(' ')} />
            </button>
          </div>
        </div>
      </div>

      {recalculating && (
        <div className="absolute inset-0 rounded-xl flex items-center justify-center backdrop-blur-sm" style={{ background: 'rgba(17,24,39,0.75)' }}>
          <div className="flex items-center gap-2 px-4 py-2 rounded-lg shadow-lg" style={{ background: '#1f2937', border: '1px solid #374151' }}>
            <div className="w-3 h-3 rounded-full bg-sky-500 animate-pulse" />
            <span className="text-sm font-medium text-gray-300">Re-running simulation...</span>
          </div>
        </div>
      )}
    </div>
  )
}

// ── Section 7: Collapsible round detail ───────────────────────────────────────

function RunDetails({ metadata }) {
  const [open, setOpen] = useState(false)
  if (!metadata) return null

  const rows = [
    { label: 'Run ID',               value: metadata.runId,                mono: true  },
    { label: 'Created At',           value: formatTs(metadata.createdAt),  mono: false },
    { label: 'Models',               value: metadata.modelName,            mono: false },
    { label: 'Provider',             value: metadata.modelProvider,        mono: false },
    { label: 'Prompt Version',       value: metadata.promptVersion,        mono: false },
    { label: 'Scoring Version',      value: metadata.scoringVersion,       mono: false },
    { label: 'App Version',          value: metadata.appVersion,           mono: false },
    { label: 'Temperature',          value: String(metadata.temperature),  mono: false },
    { label: 'Max Rounds',           value: String(metadata.maxRounds),    mono: false },
    { label: 'Equilibrium Δ',        value: String(metadata.equilibriumThreshold), mono: false },
    { label: 'Input Hash',           value: metadata.inputHash,            mono: true  },
  ]

  return (
    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1f2937' }}>
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between px-5 py-3.5 text-sm font-medium text-gray-500 hover:text-gray-300 transition-colors"
        style={{ background: '#0d1117' }}
      >
        <span>Run Details <span className="text-xs text-gray-600 font-normal ml-2">Audit trail</span></span>
        <span className="text-gray-600">{open ? '▲' : '▼'}</span>
      </button>

      {open && (
        <div className="px-5 py-4" style={{ background: '#111827', borderTop: '1px solid #1f2937' }}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-2">
            {rows.map(({ label, value, mono }) => (
              <div key={label} className="flex items-baseline gap-3 py-1" style={{ borderBottom: '1px solid #1f2937' }}>
                <span className="text-[10px] font-bold uppercase tracking-wider text-gray-600 shrink-0 w-36">{label}</span>
                <span className={`text-xs text-gray-300 leading-relaxed break-all ${mono ? 'font-mono' : ''}`}>{value ?? '—'}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function RoundDetail({ result }) {
  const [open, setOpen] = useState(false)
  const { rounds } = result
  const competitors = rounds?.round1?.map(r => r.competitorName) ?? []

  return (
    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1f2937' }}>
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between px-5 py-3.5 text-sm font-medium text-gray-500 hover:text-gray-300 transition-colors"
        style={{ background: '#0d1117' }}
      >
        <span>Round-by-round reasoning <span className="text-xs text-gray-600 font-normal ml-2">Supporting detail</span></span>
        <span className="text-gray-600">{open ? '▲' : '▼'}</span>
      </button>

      {open && (
        <div className="px-5 py-5 space-y-6" style={{ background: '#111827', borderTop: '1px solid #1f2937' }}>
          {competitors.map(name => {
            const roundEntries = ['round1', 'round2', 'round3']
              .map(key => rounds?.[key]?.find(r => r.competitorName === name))
              .filter(Boolean)

            const deduped = roundEntries.filter((r, i) => {
              if (i === 0) return true
              const prev = roundEntries[i - 1]
              return r.response?.primaryResponse?.type !== prev.response?.primaryResponse?.type ||
                     r.response?.primaryResponse?.magnitude !== prev.response?.primaryResponse?.magnitude
            })

            return (
              <div key={name}>
                <p className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-3">{name}</p>
                <div className="space-y-3">
                  {deduped.map((entry, i) => {
                    const pr = entry.response?.primaryResponse
                    return (
                      <div key={i} className="flex items-start gap-3">
                        <div className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold shrink-0 mt-0.5"
                          style={{ background: '#1e3a5f', color: '#7dd3fc' }}>
                          {entry.round}
                        </div>
                        <div>
                          <div className="flex items-center gap-2 flex-wrap mb-1">
                            <span className="text-sm font-medium text-gray-200">{fmt(pr?.type)}</span>
                            {pr?.magnitude > 0 && <span className="text-xs text-gray-500">{pr.magnitude}%</span>}
                            <TimingBadge timing={pr?.timing} />
                          </div>
                          {i > 0 && deduped[i-1]?.response?.primaryResponse?.type !== pr?.type && (
                            <p className="text-xs text-indigo-400 mb-1">↻ Changed from {fmt(deduped[i-1]?.response?.primaryResponse?.type)}</p>
                          )}
                          <p className="text-xs text-gray-500 leading-relaxed max-w-lg line-clamp-3">{pr?.rationale}</p>
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

// ── Tab bar ───────────────────────────────────────────────────────────────────

const TABS = [
  { id: 'decision', label: 'Decision',  hint: 'What to do'        },
  { id: 'market',   label: 'Market',    hint: 'Competitive dynamics' },
  { id: 'monitor',  label: 'Monitor',   hint: 'Post-decision tracking' },
  { id: 'audit',    label: 'Audit',     hint: 'Model transparency'  },
]

function TabBar({ activeTab, onTabChange }) {
  return (
    <div className="flex gap-1 p-1 rounded-xl" style={{ background: '#0d1117', border: '1px solid #1f2937' }}>
      {TABS.map(tab => {
        const isActive = activeTab === tab.id
        return (
          <button
            key={tab.id}
            onClick={() => onTabChange(tab.id)}
            className="flex-1 flex flex-col items-center px-3 py-2.5 rounded-lg transition-all"
            style={{
              background: isActive ? '#1e3a5f' : 'transparent',
              border: isActive ? '1px solid #2563eb' : '1px solid transparent',
            }}
          >
            <span className={`text-xs font-bold uppercase tracking-wider ${isActive ? 'text-sky-300' : 'text-gray-600'}`}>
              {tab.label}
            </span>
            <span className="text-[10px] mt-0.5" style={{ color: isActive ? '#60a5fa' : '#374151' }}>
              {tab.hint}
            </span>
          </button>
        )
      })}
    </div>
  )
}

function ViewToggle({ viewMode, onToggle }) {
  return (
    <div className="flex items-center justify-end gap-3">
      <span className="text-xs text-gray-600">View</span>
      <div className="flex rounded-lg overflow-hidden" style={{ border: '1px solid #1f2937' }}>
        {[
          { id: 'exec',    label: 'Exec',    title: '60-second boardroom view' },
          { id: 'analyst', label: 'Analyst', title: 'Full analysis' },
        ].map(({ id, label, title }) => {
          const active = viewMode === id
          return (
            <button
              key={id}
              onClick={onToggle}
              title={title}
              className="px-3 py-1.5 text-xs font-semibold transition-all"
              style={{
                background: active ? '#1e3a5f' : '#0d1117',
                color: active ? '#7dd3fc' : '#4b5563',
                borderRight: id === 'exec' ? '1px solid #1f2937' : undefined,
              }}
            >
              {label}
            </button>
          )
        })}
      </div>
    </div>
  )
}

// ── Main export ───────────────────────────────────────────────────────────────

export default function SimulationResults({ result, yourCompany, rawCompetitors }) {
  const [currentResult, setCurrentResult] = useState(result)
  const out = { ...(currentResult.orchestratorOutput ?? {}), _yourCompanyName: currentResult.simulationMetadata?.yourCompany?.name ?? yourCompany?.name }
  const ec = out.evidenceClassification ?? null

  const [activeTab, setActiveTab] = useState(() =>
    sessionStorage.getItem('competitorSim_activeTab') ?? 'decision'
  )
  const [viewMode, setViewMode] = useState(() =>
    sessionStorage.getItem('competitorSim_viewMode') ?? 'exec'
  )

  useEffect(() => { setCurrentResult(result) }, [result])

  function handleTabChange(tab) {
    setActiveTab(tab)
    sessionStorage.setItem('competitorSim_activeTab', tab)
  }

  function handleViewToggle() {
    const next = viewMode === 'exec' ? 'analyst' : 'exec'
    setViewMode(next)
    sessionStorage.setItem('competitorSim_viewMode', next)
    if (next === 'exec') handleTabChange('decision')
  }

  const isExec    = viewMode === 'exec'
  const tab       = isExec ? 'decision' : activeTab

  return (
    <div className="space-y-4">
      {/* Always visible */}
      <VerdictBanner out={out} result={currentResult} />

      {/* View toggle + tab bar */}
      <ViewToggle viewMode={viewMode} onToggle={handleViewToggle} />
      {!isExec && <TabBar activeTab={activeTab} onTabChange={handleTabChange} />}

      {/* ── DECISION tab ─────────────────────────────────────────────────── */}
      {tab === 'decision' && (
        <div className="space-y-4">
          <DecisionBriefCard brief={out.decisionBrief} ec={ec} />
          <PriorityActionsPanel actions={out.priorityActions} ec={ec} />
          <StrategicOptionsTable options={out.strategicOptions} />
          <RecommendationChangeTriggers triggers={out.recommendationChangeTriggers} />
        </div>
      )}

      {/* ── MARKET tab ───────────────────────────────────────────────────── */}
      {tab === 'market' && (
        <div className="space-y-4">
          <RecommendationPanel out={out} ec={ec} />
          <CompetitiveResponseMatrix result={currentResult} />
          <ScenarioOutcomes bands={out.confidenceBands} ec={ec} />
          {yourCompany && rawCompetitors && (
            <SensitivityPanel
              baseResult={currentResult}
              yourCompany={yourCompany}
              rawCompetitors={rawCompetitors}
              onResultUpdate={setCurrentResult}
            />
          )}
        </div>
      )}

      {/* ── MONITOR tab ──────────────────────────────────────────────────── */}
      {tab === 'monitor' && (
        <div className="space-y-4">
          {out.monitoringPlan
            ? <MonitoringPlan plan={out.monitoringPlan} />
            : <Watchpoints signals={out.watchlistSignals} risks={out.keyRisks} ec={ec} />
          }
        </div>
      )}

      {/* ── AUDIT tab ────────────────────────────────────────────────────── */}
      {tab === 'audit' && (
        <div className="space-y-4">
          <AssumptionsUsedTable assumptions={out.assumptionsUsed} />
          {ec && <EvidenceLegend />}
          <RoundDetail result={currentResult} />
          <RunDetails metadata={currentResult.runMetadata} />
        </div>
      )}
    </div>
  )
}
